function norm(v){return String(v??'').trim()}function lower(v){return norm(v).toLowerCase()}function first(...vals){for(const v of vals){if(v!==undefined&&v!==null&&String(v).trim()!=='')return String(v).trim()}return ''}
function addDays(dateStr,days){const d=dateStr?new Date(dateStr):new Date(); if(Number.isNaN(d.getTime())) return new Date(Date.now()+days*86400000).toISOString().slice(0,10); d.setDate(d.getDate()+days); return d.toISOString().slice(0,10)}
async function ensure(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS reaudits (id INTEGER PRIMARY KEY AUTOINCREMENT,audit_ref TEXT,engineer_name TEXT,due_date TEXT,completed_date TEXT,status TEXT DEFAULT 'Open',created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`).run()}
function parseJson(r){try{return r.audit_json?JSON.parse(r.audit_json):{}}catch(e){return {}}}
function normaliseAudit(a){const j=parseJson(a);return {...j,...a,engineer_name:first(a.engineer_name,j.engineer_name,j.engineer,j.aEngineer,j.engineerName),audit_date:first(a.audit_date,j.audit_date,j.date,j.aDate,a.created_at),score:Number(a.score??j.score??0),result:first(a.result,j.result)}}
function refFor(a){return a.audit_ref||a.ref||(a.id?`HBS-${a.id}`:'')}
function safety(a){const j=parseJson(a);const qs=Array.isArray(j.questions)?j.questions:(Array.isArray(a.questions)?a.questions:[]);const cls=norm(j.classification||j.safety_classification||a.classification||a.safety_classification).toUpperCase();if(['ID','AR'].includes(cls)) return true;return qs.some(q=>{const sec=lower(q.section), question=lower(q.question), response=lower(q.response||q.response_value||q.score||q.assessment);const crit=sec.includes('safety')||question.includes('ventilation')||question.includes('flue')||question.includes('tightness')||question.includes('isolation')||question.includes('defects classified');return crit&&(response.includes('fail')||response==='0')})}
async function backfill(env){const rows=await env.DB.prepare('SELECT * FROM audits ORDER BY id DESC').all().catch(()=>({results:[]}));for(const raw of rows.results||[]){const a=normaliseAudit(raw);const score=Number(a.score||0);if(score>0&&(score<85||safety(a))){const ref=refFor(a), engineer=a.engineer_name;if(!ref||!engineer) continue;const existing=await env.DB.prepare(`SELECT id FROM reaudits WHERE lower(engineer_name)=lower(?) AND audit_ref=? AND lower(COALESCE(status,'Open')) NOT IN ('completed','closed') LIMIT 1`).bind(engineer,ref).first().catch(()=>null);if(!existing) await env.DB.prepare('INSERT INTO reaudits (audit_ref,engineer_name,due_date,status) VALUES (?,?,?,?)').bind(ref,engineer,addDays(a.audit_date||a.created_at,30),'Open').run()}}}
export async function onRequestGet({request,env}){try{await ensure(env);await backfill(env);const u=new URL(request.url),role=u.searchParams.get('role')||'engineer',eng=u.searchParams.get('engineer')||'';let rows;if(role==='manager')rows=await env.DB.prepare('SELECT * FROM reaudits ORDER BY id DESC').all();else if(role==='senior_engineer')rows={results:[]};else rows=await env.DB.prepare('SELECT * FROM reaudits WHERE lower(engineer_name)=lower(?) ORDER BY id DESC').bind(eng).all();return Response.json({ok:true,reaudits:rows.results||[]})}catch(e){return Response.json({ok:false,error:e.message},{status:500})}}
