async function cols(env,table){try{return((await env.DB.prepare(`PRAGMA table_info(${table})`).all()).results||[]).map(c=>c.name)}catch(e){return[]}}
async function ensureColumn(env,table,name,type){const c=await cols(env,table);if(!c.includes(name)){try{await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${name} ${type}`).run()}catch(e){}}}
async function ensure(env){
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS toolbox_results (id INTEGER PRIMARY KEY AUTOINCREMENT,engineer_name TEXT,test_type TEXT,level TEXT,score REAL,result TEXT,status TEXT DEFAULT 'Pending Manager Review',answers_json TEXT,manager_name TEXT,manager_notes TEXT,signed_off_at TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS toolbox_tests (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT UNIQUE,description TEXT,pass_mark INTEGER DEFAULT 90,active INTEGER DEFAULT 1,created_by TEXT,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS toolbox_questions (id INTEGER PRIMARY KEY AUTOINCREMENT,test_id INTEGER,question TEXT,option_a TEXT,option_b TEXT,option_c TEXT,option_d TEXT,correct_answer TEXT,explanation TEXT,sort_order INTEGER DEFAULT 0,active INTEGER DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`).run();
 await ensureColumn(env,'toolbox_results','level','TEXT');
}
function isManager(role){return ['manager','director','admin','compliance manager'].includes(String(role||'').toLowerCase())}
function norm(v){return String(v||'').trim()}
function mapQuestion(q,i){const opts=q.options||[];return {question:norm(q.question),option_a:norm(opts[0]||q.option_a),option_b:norm(opts[1]||q.option_b),option_c:norm(opts[2]||q.option_c),option_d:norm(opts[3]||q.option_d),correct_answer:norm(q.correct||q.correct_answer),explanation:norm(q.explanation),sort_order:Number(q.sort_order||i+1)}}
async function getDefinitions(env,id){await ensure(env);let tests;if(id){tests=(await env.DB.prepare('SELECT * FROM toolbox_tests WHERE id=?').bind(Number(id)).all()).results||[]}else{tests=(await env.DB.prepare('SELECT t.*, (SELECT COUNT(*) FROM toolbox_questions q WHERE q.test_id=t.id AND COALESCE(q.active,1)=1) question_count FROM toolbox_tests t WHERE COALESCE(active,1)=1 ORDER BY title').all()).results||[]}for(const t of tests){const qs=(await env.DB.prepare('SELECT * FROM toolbox_questions WHERE test_id=? AND COALESCE(active,1)=1 ORDER BY sort_order,id').bind(Number(t.id)).all()).results||[];t.question_count=qs.length;t.questions=qs.map(q=>({id:q.id,question:q.question,options:[q.option_a,q.option_b,q.option_c,q.option_d].filter(Boolean),correct:q.correct_answer,explanation:q.explanation||''}))}return tests}
export async function onRequestGet({request,env}){try{await ensure(env);const u=new URL(request.url);const mode=u.searchParams.get('mode')||'';if(mode==='definitions'){const id=u.searchParams.get('id');return Response.json({ok:true,tests:await getDefinitions(env,id)})}const role=u.searchParams.get('role')||'engineer',eng=u.searchParams.get('engineer')||'';let rows;if(isManager(role))rows=await env.DB.prepare('SELECT * FROM toolbox_results ORDER BY id DESC').all();else rows=await env.DB.prepare('SELECT * FROM toolbox_results WHERE lower(engineer_name)=lower(?) ORDER BY id DESC').bind(eng).all();return Response.json({ok:true,results:rows.results||[]})}catch(e){return Response.json({ok:false,error:e.message},{status:500})}}
export async function onRequestPost({request,env}){try{await ensure(env);const u=new URL(request.url);const mode=u.searchParams.get('mode')||'';const b=await request.json();if(mode==='definitions'){if(!isManager(b.role))return Response.json({ok:false,error:'Manager access required'},{status:403});const title=norm(b.title);if(!title)throw new Error('Test title is required.');const pass=Number(b.pass_mark||90);const existing=await env.DB.prepare('SELECT id FROM toolbox_tests WHERE lower(title)=lower(?)').bind(title).first().catch(()=>null);let testId;if(existing){testId=existing.id;await env.DB.prepare('UPDATE toolbox_tests SET pass_mark=?,description=?,active=1,created_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(pass,b.description||'',b.manager_name||'',testId).run();await env.DB.prepare('UPDATE toolbox_questions SET active=0 WHERE test_id=?').bind(testId).run()}else{const ins=await env.DB.prepare('INSERT INTO toolbox_tests (title,description,pass_mark,active,created_by) VALUES (?,?,?,?,?)').bind(title,b.description||'',pass,1,b.manager_name||'').run();testId=ins.meta?.last_row_id}const questions=(b.questions||[]).map(mapQuestion).filter(q=>q.question&&q.option_a&&q.option_b&&q.correct_answer);for(const q of questions){await env.DB.prepare('INSERT INTO toolbox_questions (test_id,question,option_a,option_b,option_c,option_d,correct_answer,explanation,sort_order,active) VALUES (?,?,?,?,?,?,?,?,?,1)').bind(testId,q.question,q.option_a,q.option_b,q.option_c,q.option_d,q.correct_answer,q.explanation,q.sort_order).run()}return Response.json({ok:true,id:testId,questions:questions.length})}
const ins=await env.DB.prepare(`INSERT INTO toolbox_results (engineer_name,test_type,score,result,status,answers_json,manager_name,manager_notes) VALUES (?,?,?,?,?,?,?,?)`).bind(b.engineer_name||'',b.test_type||'Toolbox Test',Number(b.score||0),b.result||'',b.status||'Pending Manager Review',b.answers_json||'{}',b.manager_name||'',b.manager_notes||'').run();return Response.json({ok:true,id:ins.meta?.last_row_id})}catch(e){return Response.json({ok:false,error:e.message},{status:500})}}
export async function onRequestPut({request,env}){try{await ensure(env);const b=await request.json();await env.DB.prepare('UPDATE toolbox_results SET status=?, manager_name=?, manager_notes=?, signed_off_at=? WHERE id=?').bind(b.status||'Completed',b.manager_name||'',b.manager_notes||'',new Date().toISOString(),Number(b.id)).run();return Response.json({ok:true,id:b.id})}catch(e){return Response.json({ok:false,error:e.message},{status:500})}}
